apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .env: REFUQUJBU0VfVVJMPSJteXNxbDovL2Vjb20tZGI6MzMwNi9zaG9wIgpDQUNIRV9TSVpFPSIxMDAwIgpQQVlNRU5UX0dBVEVXQVk9Imh0dHBzOi8vcGF5bWVudC1nYXRld2F5LmV4YW1wbGUuY29tIgpNQVhfQ0FSVF9JVEVNUz01MCIKU0VTU0lPTl9USU1FT1VUPSIzNjAwIg==